# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 605)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 65, 65))
        self.pushButton_2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_2.setText("")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 10, 65, 65))
        self.pushButton_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_3.setText("")
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 10, 65, 65))
        self.pushButton_4.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_4.setText("")
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 10, 65, 65))
        self.pushButton_5.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_5.setText("")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 10, 65, 65))
        self.pushButton_6.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_6.setText("")
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(500, 10, 65, 65))
        self.pushButton_7.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_7.setText("")
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 10, 65, 65))
        self.pushButton_8.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_8.setText("")
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 10, 65, 65))
        self.pushButton_9.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_9.setText("")
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 80, 65, 65))
        self.pushButton_10.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_10.setText("")
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(360, 80, 65, 65))
        self.pushButton_11.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_11.setText("")
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 80, 65, 65))
        self.pushButton_12.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_12.setText("")
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 80, 65, 65))
        self.pushButton_13.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_13.setText("")
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 80, 65, 65))
        self.pushButton_14.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_14.setText("")
        self.pushButton_14.setAutoDefault(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(80, 80, 65, 65))
        self.pushButton_15.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_15.setText("")
        self.pushButton_15.setAutoDefault(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(430, 80, 65, 65))
        self.pushButton_16.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_16.setText("")
        self.pushButton_16.setAutoDefault(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(500, 80, 65, 65))
        self.pushButton_17.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_17.setText("")
        self.pushButton_17.setAutoDefault(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(360, 220, 65, 65))
        self.pushButton_18.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_18.setText("")
        self.pushButton_18.setAutoDefault(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 220, 65, 65))
        self.pushButton_19.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_19.setText("")
        self.pushButton_19.setAutoDefault(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(430, 220, 65, 65))
        self.pushButton_20.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_20.setText("")
        self.pushButton_20.setAutoDefault(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(500, 220, 65, 65))
        self.pushButton_21.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_21.setText("")
        self.pushButton_21.setAutoDefault(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(80, 150, 65, 65))
        self.pushButton_22.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_22.setText("")
        self.pushButton_22.setAutoDefault(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(290, 220, 65, 65))
        self.pushButton_23.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_23.setText("")
        self.pushButton_23.setAutoDefault(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(290, 150, 65, 65))
        self.pushButton_24.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_24.setText("")
        self.pushButton_24.setAutoDefault(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(360, 150, 65, 65))
        self.pushButton_25.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_25.setText("")
        self.pushButton_25.setAutoDefault(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(220, 150, 65, 65))
        self.pushButton_26.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_26.setText("")
        self.pushButton_26.setAutoDefault(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(150, 150, 65, 65))
        self.pushButton_27.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_27.setText("")
        self.pushButton_27.setAutoDefault(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 150, 65, 65))
        self.pushButton_28.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_28.setText("")
        self.pushButton_28.setAutoDefault(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(500, 150, 65, 65))
        self.pushButton_29.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_29.setText("")
        self.pushButton_29.setAutoDefault(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(10, 220, 65, 65))
        self.pushButton_30.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_30.setText("")
        self.pushButton_30.setAutoDefault(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(430, 150, 65, 65))
        self.pushButton_31.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_31.setText("")
        self.pushButton_31.setAutoDefault(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(150, 220, 65, 65))
        self.pushButton_32.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_32.setText("")
        self.pushButton_32.setAutoDefault(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(80, 220, 65, 65))
        self.pushButton_33.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_33.setText("")
        self.pushButton_33.setAutoDefault(False)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(220, 500, 65, 65))
        self.pushButton_34.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_34.setText("")
        self.pushButton_34.setAutoDefault(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(220, 290, 65, 65))
        self.pushButton_35.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_35.setText("")
        self.pushButton_35.setAutoDefault(False)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(430, 290, 65, 65))
        self.pushButton_36.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_36.setText("")
        self.pushButton_36.setAutoDefault(False)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(500, 360, 65, 65))
        self.pushButton_37.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_37.setText("")
        self.pushButton_37.setAutoDefault(False)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(10, 500, 65, 65))
        self.pushButton_38.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_38.setText("")
        self.pushButton_38.setAutoDefault(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setGeometry(QtCore.QRect(10, 360, 65, 65))
        self.pushButton_39.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_39.setText("")
        self.pushButton_39.setAutoDefault(False)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(150, 360, 65, 65))
        self.pushButton_40.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_40.setText("")
        self.pushButton_40.setAutoDefault(False)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(500, 430, 65, 65))
        self.pushButton_41.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_41.setText("")
        self.pushButton_41.setAutoDefault(False)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setGeometry(QtCore.QRect(430, 430, 65, 65))
        self.pushButton_42.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_42.setText("")
        self.pushButton_42.setAutoDefault(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setGeometry(QtCore.QRect(10, 290, 65, 65))
        self.pushButton_43.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_43.setText("")
        self.pushButton_43.setAutoDefault(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setGeometry(QtCore.QRect(290, 290, 65, 65))
        self.pushButton_44.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_44.setText("")
        self.pushButton_44.setAutoDefault(False)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setGeometry(QtCore.QRect(150, 500, 65, 65))
        self.pushButton_45.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_45.setText("")
        self.pushButton_45.setAutoDefault(False)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setGeometry(QtCore.QRect(150, 290, 65, 65))
        self.pushButton_46.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_46.setText("")
        self.pushButton_46.setAutoDefault(False)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_47.setGeometry(QtCore.QRect(290, 500, 65, 65))
        self.pushButton_47.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_47.setText("")
        self.pushButton_47.setAutoDefault(False)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_48.setGeometry(QtCore.QRect(430, 360, 65, 65))
        self.pushButton_48.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_48.setText("")
        self.pushButton_48.setAutoDefault(False)
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_49.setGeometry(QtCore.QRect(360, 360, 65, 65))
        self.pushButton_49.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_49.setText("")
        self.pushButton_49.setAutoDefault(False)
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50.setGeometry(QtCore.QRect(360, 430, 65, 65))
        self.pushButton_50.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_50.setText("")
        self.pushButton_50.setAutoDefault(False)
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_51.setGeometry(QtCore.QRect(10, 430, 65, 65))
        self.pushButton_51.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_51.setText("")
        self.pushButton_51.setAutoDefault(False)
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_52.setGeometry(QtCore.QRect(220, 360, 65, 65))
        self.pushButton_52.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_52.setText("")
        self.pushButton_52.setAutoDefault(False)
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_53.setGeometry(QtCore.QRect(150, 430, 65, 65))
        self.pushButton_53.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_53.setText("")
        self.pushButton_53.setAutoDefault(False)
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_54.setGeometry(QtCore.QRect(360, 500, 65, 65))
        self.pushButton_54.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_54.setText("")
        self.pushButton_54.setAutoDefault(False)
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_55.setGeometry(QtCore.QRect(290, 360, 65, 65))
        self.pushButton_55.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_55.setText("")
        self.pushButton_55.setAutoDefault(False)
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_56.setGeometry(QtCore.QRect(290, 430, 65, 65))
        self.pushButton_56.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_56.setText("")
        self.pushButton_56.setAutoDefault(False)
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_57.setGeometry(QtCore.QRect(80, 500, 65, 65))
        self.pushButton_57.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_57.setText("")
        self.pushButton_57.setAutoDefault(False)
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_58.setGeometry(QtCore.QRect(80, 290, 65, 65))
        self.pushButton_58.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_58.setText("")
        self.pushButton_58.setAutoDefault(False)
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_59.setGeometry(QtCore.QRect(430, 500, 65, 65))
        self.pushButton_59.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_59.setText("")
        self.pushButton_59.setAutoDefault(False)
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_60.setGeometry(QtCore.QRect(80, 360, 65, 65))
        self.pushButton_60.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_60.setText("")
        self.pushButton_60.setAutoDefault(False)
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_61 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_61.setGeometry(QtCore.QRect(500, 500, 65, 65))
        self.pushButton_61.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_61.setText("")
        self.pushButton_61.setAutoDefault(False)
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_62.setGeometry(QtCore.QRect(500, 290, 65, 65))
        self.pushButton_62.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_62.setText("")
        self.pushButton_62.setAutoDefault(False)
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_63.setGeometry(QtCore.QRect(80, 430, 65, 65))
        self.pushButton_63.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_63.setText("")
        self.pushButton_63.setAutoDefault(False)
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_64.setGeometry(QtCore.QRect(360, 290, 65, 65))
        self.pushButton_64.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_64.setText("")
        self.pushButton_64.setAutoDefault(False)
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_65.setGeometry(QtCore.QRect(220, 430, 65, 65))
        self.pushButton_65.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 146, 59);")
        self.pushButton_65.setText("")
        self.pushButton_65.setAutoDefault(False)
        self.pushButton_65.setObjectName("pushButton_65")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 25))
        self.menubar.setStyleSheet("background-color: rgb(0, 128, 255);\n"
"selection-color: rgb(128, 255, 0);\n"
"border-color: rgb(102, 102, 255);\n"
"font-color: rgb(0, 128, 255);\n"
"font: 14pt \"Courier\";")
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setStyleSheet("background-color: rgb(0, 128, 255);\n"
"selection-color: rgb(128, 255, 0);\n"
"border-color: rgb(102, 102, 255);\n"
"font-color: rgb(255, 255, 255);\n"
"font: 14pt \"Courier\";")
        self.menuMenu.setObjectName("menuMenu")
        self.menuCtrl = QtWidgets.QMenu(self.menubar)
        self.menuCtrl.setObjectName("menuCtrl")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuCtrl.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMenu.setTitle(_translate("MainWindow", "opt"))
        self.menuCtrl.setTitle(_translate("MainWindow", "ctrl"))

